# Generated by Django 5.0.3 on 2024-12-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
