# Generated by Django 5.0.3 on 2024-12-17 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_genre',
            field=models.CharField(blank=True, choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Classical', 'Classical'), ('Rap', 'Rap'), ('Jazz', 'Jazz'), ('Electronic', 'Electronic'), ('Metal', 'Metal'), ('Country', 'Country')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_criteria',
            field=models.CharField(choices=[('Lyricism', 'Lyricism'), ('Melody', 'Melody'), ('Instrumentals', 'Instrumentals'), ('Vocals', 'Vocals')], default='Melody', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
