# Generated by Django 5.0.3 on 2024-12-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
